name: "build"

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  windows:
    strategy:
      matrix:
        include:
          - toolchain: 2019
            runtime: MD
            options: ""
          - toolchain: 2019
            runtime: MDd
            options: "--enable-debug --disable-release"

    runs-on: windows-${{ matrix.toolchain }}
    name: VS${{ matrix.toolchain }}_${{ matrix.runtime }}

    steps:
      - name: Setup Git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            base-devel
            binutils
            make
            perl
            python

      - name: Setup flags
        shell: msys2 {0}
        run: |
          echo BUILD_PATH=$(echo "$PATH" | perl -pe \
            's,^(.+?):(/c/Program Files.+?/VC/Tools/MSVC/.+?/HostX64/x64):(.*)$,$2:$1:$3,') \
            >> $GITHUB_ENV
          echo BUILD_FLAGS=/std:c++17 \
            >> $GITHUB_ENV

      - name: Configure
        shell: msys2 {0}
        run: |
          cd icu/icu4c/source
          export PATH="${{ env.BUILD_PATH }}"
          export CXXFLAGS="${{ env.BUILD_FLAGS }}"
          which cl
          which link
          ./runConfigureICU ${{ matrix.options }} MSYS/MSVC \
            --enable-static \
            --disable-shared \
            --disable-tests \
            --disable-strict \
            --disable-tools \
            --disable-extras \
            --disable-icuio \
            --disable-tests \
            --disable-samples \
            --prefix=$PWD/../../../../dist

      - name: Build
        shell: msys2 {0}
        run: |
          cd icu/icu4c/source
          export PATH="${{ env.BUILD_PATH }}"
          export CXXFLAGS="${{ env.BUILD_FLAGS }}"
          which cl
          which link
          make -j2

      - name: Install
        shell: msys2 {0}
        run: |
          cd icu/icu4c/source
          make install

      - name: Clean
        shell: msys2 {0}
        run: |
          cd icu/icu4c/source
          make clean

      - name: Deploy
        shell: pwsh
        run: |
          cd icu
          $git_branch = "VS${{ matrix.toolchain }}_${{ matrix.runtime }}"
          $git_tag = git describe --tags --abbrev=0
          $git_tag = $git_tag + "_" + $git_branch
          cd ..
          git checkout ${git_branch}
          if (test-path bin) {
            rm -r bin
          }
          if (test-path include) {
            rm -r include
          }
          if (test-path lib) {
            rm -r lib
          }
          if (test-path share) {
            rm -r share
          }
          mv ../dist/bin .
          mv ../dist/include .
          mv ../dist/lib .
          mv ../dist/share .
          git add bin
          git add include
          git add lib
          git add share
          git config user.email "actions-bot@users.noreply.github.com"
          git config user.name "actions-bot"
          git commit --allow-empty -m"Deploy ICU ${git_tag}"
          git push -f origin ${git_branch}:${git_branch}
          git tag -f ${git_tag}
          git push -f origin :refs/tags/${git_tag}
          git push -f origin ${git_tag}

  macos:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Configure
        run: |
          cd icu/icu4c/source
          export CFLAGS="-std=c11 -fPIC -O2 -mmacosx-version-min=10.15 -arch x86_64 -arch arm64"
          export CXXFLAGS="-std=c++17 -fPIC -O2 -mmacosx-version-min=10.15 -arch x86_64 -arch arm64"
          export LDFLAGS="-lc++ -mmacosx-version-min=10.15 -arch x86_64 -arch arm64"
          ./configure \
            --enable-static \
            --disable-shared \
            --disable-tests \
            --disable-strict \
            --disable-tools \
            --disable-extras \
            --disable-icuio \
            --disable-tests \
            --disable-samples

      - name: Build
        run: |
          cd icu/icu4c/source
          make -j4 VERBOSE=1

      - name: Install
        run: |
          destdir="$(cd .. && pwd)"/dist
          cd icu/icu4c/source
          make install DESTDIR=${destdir}

      - name: Clean
        run: |
          cd icu/icu4c/source
          make clean

      - name: Deploy
        run: |
          cd icu
          git_branch="macos"
          git_tag="$(git describe --tags --abbrev=0)_macos"
          cd ..
          git checkout ${git_branch}
          rm -rf bin
          rm -rf include
          rm -rf lib
          rm -rf share
          mv ../dist/usr/local/bin .
          mv ../dist/usr/local/include .
          mv ../dist/usr/local/lib .
          mv ../dist/usr/local/share .
          git add bin
          git add include
          git add lib
          git add share
          git config user.email "actions-bot@users.noreply.github.com"
          git config user.name "actions-bot"
          git commit --allow-empty -m"Deploy ICU ${git_tag}"
          git push -f origin ${git_branch}:${git_branch}
          git tag -f ${git_tag}
          git push origin :refs/tags/${git_tag}
          git push origin ${git_tag}
